@startuml

!pragma layout smetana
!define JAVA_STYLE

abstract class Simulator {
  + {abstract} create(file_name_args: String): Simulator
  + {abstract} listAgents(): List[Agents]
  + {abstract} execute(): void
}

class SimulatorMotor {
  - time_limit: int
  - time_per_step: float
  - running: bool
  - world: World
  - states: List[State]
  + isSolved(): boolean
  + shutDownSimulation(): void
  + saveResults(fileName: String): void
  + saveState(): void
}

abstract class Agent {
  + {abstract} create(fileNameArgs: String): Agent
  + {abstract} observe(observation: Observation): void
  + {abstract} act(): Action
  + {abstract} evaluateCurrentState(reward: float)
  + {abstract} install(sensor: Sensor): void
  + {abstract} execute(): void
}

class ExplorerAgent {
  - id: int
  - position: tuple
  - learn_mode: boolean
  - steps: steps
  - genotype: List[Action]
  - sensor: Sensor
  - observation: set
  - step_index: int
  - inventory: List[Item]
  - behavior: set
  - path: List[tuple]
  - reward: int
  - noveltyScore: float
  - combinedFitness: float
  + storeItem(item: Pickable): void
  + discardItem(item: Pickable): void
}

class Chicken {
}

enum Action {
  MOVE_NORTH = (0, 1)
  MOVE_SOUTH = (0, -1)
  MOVE_WEST = (-1, 0)
  MOVE_EAST = (1, 0)
  ---
  + random_action(): tuple
}

enum Direction {
  NORTH = (0, 1)
  SOUTH = (0, -1)
  WEST  = (-1, 0)
  EAST  = (1, 0)
  NORTH_EAST = (1, 1)
  NORTH_WEST = (-1, 1)
  SOUTH_EAST = (1, -1)
  SOUTH_WEST = (-1, -1)
}

abstract class Environment {
  + {abstract} observationFor(explorer: ExplorerAgent): Observation
  + {abstract} update(): void
  + {abstract} act(action: Action, agent: Agent): void
}

class World {
  - width: int
  - height: int
  - solved: boolean
  - map: List[List]
  - agents: List[Chicken]
  + initializeMap(): void
  + is_solved(): boolean
  + is_valid_action(action_to_validate: Action, explorer: ExplorerAgent): tuple
}

class ForagingWorld {
  + stones: List[Stone]
  + nests: List[Nest]
  + eggs: List[Egg]
}

class CoopWorld {
  + chicken_coop: ChickenCoop
}

class Observation {
  - agent_id: int
  - possible_actions: List
  + total_possible_actions(): int
}

class Wall {
}

abstract class Item {
  # name: String
  # id: int
  # position: tuple
}

class Pickable {
  - picked_up: boolean
  - value: int
  + pickUp(): void
  + drop(): void
}

class Nest {
  - capacity: int
  - num_of_items: int
  + put(num_of_items: int): boolean
}

class Egg {
}

class ChickenCoop {
}

class Stone {
}

class Sensor {
  - world: World
  - height: int
  - width: int
  - max_range: int
  + get_observation(explorer: ExplorerAgent): Observation
  + _cast_ray(start_pos: tuple, step_vector: tuple)
}

'TODO - Class state
'TODO - check class relations !

Simulator <|-- SimulatorMotor
SimulatorMotor "1" -- "1" World

World "1" -- "0..*" Item

Environment <|-- World
World <|-- ForagingWorld
ForagingWorld "1" -- "1..*" Nest
ForagingWorld "1" -- "1..*" Stone
ForagingWorld "1" -- "1..*" Egg

World <|-- CoopWorld
CoopWorld "1" -- "1" ChickenCoop
CoopWorld "1" -- "1..*" Wall

Agent <|-- ExplorerAgent
ExplorerAgent "1..*" -- "1" World
ExplorerAgent "1" --- "0, 1" Sensor
ExplorerAgent <|-- Chicken
ExplorerAgent "1" -- "0, 1" Observation

Item <|--- Wall
Item <|-- Pickable
Item <|-- ChickenCoop
Item <|-- Nest

Pickable <|-- Egg
Pickable <|-- Stone

Direction --> Sensor
Action --> ExplorerAgent

@enduml